// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
      process.env["DATABASE_URL"] ||
      "postgresql://neondb_owner:npg_BX7Rakof0USN@ep-summer-dream-ayv5d4yp-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require",
  },
});
